### ISSUE TITLE
netlify deploy bug

### ISSUE THREAD

**Issue by PeterSulcs** [PHM-Data-Hub/app#23]
@mattsul @cbarnes7 @pjw901015 

I think Matt was the one that mentioned this issue, but the netlify build is failing with the following logs:

```
2:31:39 PM:   Error message
2:31:39 PM:   /opt/build/repo/next.config.js:4
2:31:39 PM:     publicRuntimeConfig: {
2:31:39 PM:     ^^^^^^^^^^^^^^^^^^^
2:31:39 PM: ​
2:31:39 PM:   SyntaxError: missing ) after argument list
2:31:39 PM: ​
2:31:39 PM:   Plugin details
2:31:39 PM:   Package:        @netlify/plugin-nextjs
2:31:39 PM:   Version:        2.0.0
2:31:39 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
2:31:39 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
2:31:39 PM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
2:31:39 PM: ​
2:31:39 PM:   Error location
2:31:39 PM:   In "onPreBuild" event in "@netlify/plugin-nextjs" from netlify.toml
2:31:39 PM:       at wrapSafe (internal/modules/cjs/loader.js:1047:16)
2:31:39 PM:       at Module._compile (internal/modules/cjs/loader.js:1097:27)
2:31:39 PM:       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
2:31:39 PM:       at Module.load (internal/modules/cjs/loader.js:977:32)
2:31:39 PM:       at Function.Module._load (internal/modules/cjs/loader.js:877:14)
2:31:39 PM:       at Module.require (internal/modules/cjs/loader.js:1019:19)
2:31:39 PM:       at require (internal/modules/cjs/helpers.js:77:18)
2:31:39 PM:       at loadConfig (/opt/build/repo/node_modules/next/dist/next-server/server/config.js:8:94)
2:31:39 PM:       at onPreBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:57:26)
2:31:39 PM:       at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3)
2:31:39 PM: ​
2:31:39 PM:   Resolved config
2:31:39 PM:   build:
2:31:39 PM:     command: npm run build
2:31:39 PM:     commandOrigin: ui
2:31:39 PM:     environment:
2:31:39 PM:       - REVIEW_ID
2:31:39 PM:     publish: /opt/build/repo/.next
2:31:39 PM:   plugins:
2:31:39 PM:     - inputs: {}
2:31:39 PM:       origin: config
2:31:39 PM:       package: '@netlify/plugin-nextjs'
2:31:39 PM: Caching artifacts
2:31:39 PM: Started saving node modules
2:31:39 PM: Finished saving node modules
2:31:39 PM: Started saving build plugins
2:31:39 PM: Finished saving build plugins
2:31:39 PM: Started saving pip cache
2:31:39 PM: Finished saving pip cache
2:31:39 PM: Started saving emacs cask dependencies
2:31:39 PM: Finished saving emacs cask dependencies
2:31:39 PM: Started saving maven dependencies
2:31:39 PM: Finished saving maven dependencies
2:31:39 PM: Started saving boot dependencies
2:31:39 PM: Finished saving boot dependencies
2:31:39 PM: Started saving rust rustup cache
2:31:39 PM: Finished saving rust rustup cache
2:31:39 PM: Started saving go dependencies
2:31:39 PM: Finished saving go dependencies
2:31:42 PM: Build failed due to a plugin error: Build script returned non-zero exit code: 3
2:31:42 PM: Failing build: Failed to build site
2:31:42 PM: Failed during stage 'building site': Build script returned non-zero exit code: 3
2:31:42 PM: Finished processing build request in 52.267591419s
```

**Comment by PeterSulcs** [comment]
I found this documentation about that config file. https://nextjs.org/docs/api-reference/next.config.js/introduction

**Comment by mattsul** [comment]
Thank you! Will look into it! 👍 😄

**Comment by PeterSulcs** [comment]
I did try adding that CI envar mentioned at the link in your PR and retried the deploy:

```


Skip to main content
Netlify
Peter Sulcs's team
quirky-meninsky-24e642
Notifications






























Support










Deploys
Deploy details
Deploy failed
Deploy Preview #22: pre-design-render@e1b1747. Today at 10:28 AM

Deploy failed due to an error in @netlify/plugin-nextjs plugin.

Deploy settings
Retry deploy
Deploy summary
plugin error
Plugin "@netlify/plugin-nextjs" internal error

/opt/build/repo/next.config.js:4
publicRuntimeConfig: {
^^^^^^^^^^^^^^^^^^^

SyntaxError: missing ) after argument list

Deploy log



10:28:06 AM: Build ready to start
10:28:08 AM: build-image version: d84c79427e8f83c1ba17bcdd7b3fe38059376b68
10:28:08 AM: build-image tag: v3.6.1
10:28:08 AM: buildbot version: f8648819b2de8637c0fbd87ac67f86c2856f6ad3
10:28:08 AM: Building without cache
10:28:08 AM: Starting to prepare the repo for build
10:28:08 AM: No cached dependencies found. Cloning fresh repo
10:28:08 AM: git clone https://github.com/PHM-Data-Hub/app
10:28:09 AM: Preparing Git Reference pull/22/head
10:28:11 AM: Starting build script
10:28:11 AM: Installing dependencies
10:28:11 AM: Python version set to 2.7
10:28:12 AM: v12.18.0 is already installed.
10:28:13 AM: Now using node v12.18.0 (npm v6.14.4)
10:28:13 AM: Started restoring cached build plugins
10:28:13 AM: Finished restoring cached build plugins
10:28:13 AM: Attempting ruby version 2.7.1, read from environment
10:28:15 AM: Using ruby version 2.7.1
10:28:15 AM: Using PHP version 5.6
10:28:15 AM: Started restoring cached node modules
10:28:15 AM: Finished restoring cached node modules
10:28:15 AM: Installing NPM modules using NPM version 6.14.4
10:28:31 AM: > sharp@0.26.3 install /opt/build/repo/node_modules/sharp
10:28:31 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
10:28:32 AM: info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
10:28:34 AM: > node-sass@5.0.0 install /opt/build/repo/node_modules/node-sass
10:28:34 AM: > node scripts/install.js
10:28:35 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/linux-x64-72_binding.node
10:28:35 AM: Download complete
10:28:35 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
10:28:35 AM: Caching binary to /opt/buildhome/.npm/node-sass/5.0.0/linux-x64-72_binding.node
10:28:35 AM: > @ampproject/toolbox-optimizer@2.7.1-alpha.0 postinstall /opt/build/repo/node_modules/@ampproject/toolbox-optimizer
10:28:35 AM: > node lib/warmup.js
10:28:36 AM: Browserslist: caniuse-lite is outdated. Please run:
10:28:36 AM: npx browserslist@latest --update-db
10:28:36 AM: AMP OPTIMIZER Downloaded latest AMP runtime data.
10:28:36 AM: > node-sass@5.0.0 postinstall /opt/build/repo/node_modules/node-sass
10:28:36 AM: > node scripts/build.js
10:28:36 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
10:28:36 AM: Testing binary
10:28:37 AM: Binary is fine
10:28:38 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
10:28:38 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:28:38 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
10:28:38 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:28:38 AM: added 893 packages from 536 contributors and audited 895 packages in 21.491s
10:28:38 AM: 41 packages are looking for funding
10:28:38 AM:   run `npm fund` for details
10:28:38 AM: found 0 vulnerabilities
10:28:38 AM: NPM modules installed
10:28:39 AM: Started restoring cached go cache
10:28:39 AM: Finished restoring cached go cache
10:28:39 AM: go version go1.14.4 linux/amd64
10:28:39 AM: go version go1.14.4 linux/amd64
10:28:39 AM: Installing missing commands
10:28:39 AM: Verify run directory
10:28:41 AM: ​
10:28:41 AM: ────────────────────────────────────────────────────────────────
10:28:41 AM:   Netlify Build                                                 
10:28:41 AM: ────────────────────────────────────────────────────────────────
10:28:41 AM: ​
10:28:41 AM: ❯ Version
10:28:41 AM:   @netlify/build 9.0.0
10:28:41 AM: ​
10:28:41 AM: ❯ Flags
10:28:41 AM:   deployId: 6022d436f9d5412fb5af8c41
10:28:41 AM:   mode: buildbot
10:28:41 AM: ​
10:28:41 AM: ❯ Current directory
10:28:41 AM:   /opt/build/repo
10:28:41 AM: ​
10:28:41 AM: ❯ Config file
10:28:41 AM:   /opt/build/repo/netlify.toml
10:28:41 AM: ​
10:28:41 AM: ❯ Context
10:28:41 AM:   deploy-preview
10:28:41 AM: ​
10:28:41 AM: ❯ Installing plugins
10:28:41 AM:    - @netlify/plugin-nextjs@2.0.0
10:29:00 AM: ​
10:29:00 AM: ❯ Loading plugins
10:29:00 AM:    - @netlify/plugin-nextjs@2.0.0 from netlify.toml
10:29:00 AM: ​
10:29:00 AM: ────────────────────────────────────────────────────────────────
10:29:00 AM:   1. onPreBuild command from @netlify/plugin-nextjs             
10:29:00 AM: ────────────────────────────────────────────────────────────────
10:29:00 AM: ​
10:29:00 AM: ** Warning: support for Next.js >=10.0.0 is experimental **
10:29:00 AM: ​
10:29:00 AM: ────────────────────────────────────────────────────────────────
10:29:00 AM:   Plugin "@netlify/plugin-nextjs" internal error                
10:29:00 AM: ────────────────────────────────────────────────────────────────
10:29:00 AM: ​
10:29:00 AM:   Error message
10:29:00 AM:   /opt/build/repo/next.config.js:4
10:29:00 AM:     publicRuntimeConfig: {
10:29:00 AM:     ^^^^^^^^^^^^^^^^^^^
10:29:00 AM: ​
10:29:00 AM:   SyntaxError: missing ) after argument list
10:29:00 AM: ​
10:29:00 AM:   Plugin details
10:29:00 AM:   Package:        @netlify/plugin-nextjs
10:29:00 AM:   Version:        2.0.0
10:29:00 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-nextjs.git
10:29:00 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
10:29:00 AM:   Report issues:  https://github.com/netlify/netlify-plugin-nextjs/issues
10:29:00 AM: ​
10:29:00 AM:   Error location
10:29:00 AM:   In "onPreBuild" event in "@netlify/plugin-nextjs" from netlify.toml
10:29:00 AM:       at wrapSafe (internal/modules/cjs/loader.js:1047:16)
10:29:00 AM:       at Module._compile (internal/modules/cjs/loader.js:1097:27)
10:29:00 AM:       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
10:29:00 AM:       at Module.load (internal/modules/cjs/loader.js:977:32)
10:29:00 AM:       at Function.Module._load (internal/modules/cjs/loader.js:877:14)
10:29:00 AM:       at Module.require (internal/modules/cjs/loader.js:1019:19)
10:29:00 AM:       at require (internal/modules/cjs/helpers.js:77:18)
10:29:00 AM:       at loadConfig (/opt/build/repo/node_modules/next/dist/next-server/server/config.js:8:94)
10:29:00 AM:       at onPreBuild (/opt/build/repo/.netlify/plugins/node_modules/@netlify/plugin-nextjs/index.js:57:26)
10:29:00 AM:       at async Object.run (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins/child/run.js:18:3)
10:29:00 AM: ​
10:29:00 AM:   Resolved config
10:29:00 AM:   build:
10:29:00 AM:     command: npm run build
10:29:00 AM:     commandOrigin: ui
10:29:00 AM:     environment:
10:29:00 AM:       - CI
10:29:00 AM:       - REVIEW_ID
10:29:00 AM:     publish: /opt/build/repo/.next
10:29:00 AM:   plugins:
10:29:00 AM:     - inputs: {}
10:29:00 AM:       origin: config
10:29:00 AM:       package: '@netlify/plugin-nextjs'
10:29:00 AM: Caching artifacts
10:29:00 AM: Started saving node modules
10:29:00 AM: Finished saving node modules
10:29:00 AM: Started saving build plugins
10:29:00 AM: Finished saving build plugins
10:29:00 AM: Started saving pip cache
10:29:01 AM: Finished saving pip cache
10:29:01 AM: Started saving emacs cask dependencies
10:29:01 AM: Finished saving emacs cask dependencies
10:29:01 AM: Started saving maven dependencies
10:29:01 AM: Finished saving maven dependencies
10:29:01 AM: Started saving boot dependencies
10:29:01 AM: Finished saving boot dependencies
10:29:01 AM: Started saving rust rustup cache
10:29:01 AM: Finished saving rust rustup cache
10:29:01 AM: Started saving go dependencies
10:29:01 AM: Finished saving go dependencies
10:29:03 AM: Build failed due to a plugin error: Build script returned non-zero exit code: 3
10:29:03 AM: Failing build: Failed to build site
10:29:03 AM: Failed during stage 'building site': Build script returned non-zero exit code: 3
10:29:03 AM: Finished processing build request in 55.898669417s
Docs
Pricing
Support
News
Terms
© 2021 Netlify


```
